### ISSUE TITLE
Restructure X!'s tools GUI

### ISSUE THREAD

**Issue by cyberpower678** [x-tools/xtools-legacy#1]
As it is, the interface of the tools, is both outdated and inconsistent, not to mention some if it depends on resources that no longer exist.  The graphic user interface should be updated to be consistent design.

**Comment by cyberpower678** [comment]
We should also direct source and bug report links to here now as this is the best place to manage bug reports and feature requests.

**Comment by cyberpower678** [comment]
Pcount rewritten so far.

**Comment by Hedonil** [comment]
Fixed with redesign.
