### ISSUE TITLE
Get redirects from Toolserver

### ISSUE THREAD

**Issue by nemobis** [x-tools/xtools-legacy#10]
toolserver.org/~tparis/ and toolserver.org/~soxred93/ still get a lot of traffic http://lists.wikimedia.org/pipermail/toolserver-l/2013-October/006337.html but are dead links, they should redirect to xtools.

Should be reported upstream, but TS admins don't seem to be using https://jira.toolserver.org/browse/TS , maybe ask Silke?

**Comment by Hedonil** [comment]
The path  ~soxred93/images has been fixed in .css. Requests should stop now. If so, no redirect for this resource will be necessary. I'll check this again.

**Comment by nemobis** [comment]
Not quite, especially as there are links everywhere. http://www.w3.org/Provider/Style/URI.html
I filed https://jira.toolserver.org/browse/TS-1726

**Comment by cyberpower678** [comment]
We don't respond to jira any longer.

**Comment by nosy79** [comment]
ok i can followup the jira request here:

tparis already has a redirect. Should I use this one which ends up 
here: https://tools.wmflabs.org/supercount/index.php or better http://tools.wmflabs.org/xtools/ ?

I can redirect soxred93s queries to the xtools i guess thats fine.

**Comment by nosy79** [comment]
I mailed the two maintainers of the ts accounts and will wait a week for the answer.

**Comment by nosy79** [comment]
Placed the redirects for both accounts.
Please keep in mind that http://www.toolserver.org/~tparis/pcount/ is still redirected somewhere else which is relevant as long as tparis account is not expired. Is that fine?

**Comment by cyberpower678** [comment]
Can you renew my account for me?  I currently have no access right now.

**Comment by Hedonil** [comment]
Hi Nosy79, afaict everything works fine (and no loops detected so far ;) )
http://www.toolserver.org/~soxred93/images/ -> http://tools.wmflabs.org/xtools/images  {{ok}}
http://www.toolserver.org/~soxred93/ -> http://tools.wmflabs.org/xtools/  {{ok}}
http://www.toolserver.org/~tparis/pcount/ -> http://tools.wmflabs.org/supercount/  {{ok}}
Thanks for that.

**Comment by nosy79** [comment]
Cyberpower678, I renewed your account.

**Comment by cyberpower678** [comment]
@nosy79 Thanks.

**Comment by Hedonil** [comment]
Afaics these redirects are all happy now.
