### ISSUE TITLE
Link to (commonswiki)

### ISSUE THREAD

**Issue by alanajjar** [x-tools/xtools-legacy#101]
The link to commonswiki in (SUL editcounter) must fix by add word (media) to the link,
e.g: 
The current link:
//tools.wmflabs.org/xtools-ec/?user=%D8%B9%D9%84%D8%A7%D8%A1&project=commonswiki
The fixed one:
 //tools.wmflabs.org/xtools-ec/?user=%D8%B9%D9%84%D8%A7%D8%A1&project=commonswikimedia

**Comment by Matthewrbowker** [comment]
I have fixed this issue in the rebirth, which will be deployed later this year.
