### ISSUE TITLE
General statistics Total edits is Different Than SUL editcounter

### ISSUE THREAD

**Issue by jarallah** [x-tools/xtools-legacy#103]
https://tools.wmflabs.org/xtools-ec/?user=%D8%AC%D8%A7%D8%B1+%D8%A7%D9%84%D9%84%D9%87&project=ar.wikipedia.org

The issue is General statistics Total edits is Different Than SUL editcounter the The problem of edits number has become a few days ago  Are there a solve for this issue?

**Comment by Matthewrbowker** [comment]
Appears to be a math error - I will look into it and fix if necessary.

**Comment by jarallah** [comment]
is there solve for this issue ?! my Total edits is minus more than 2000.

**Comment by Matthewrbowker** [comment]
Still working on it.  Thanks for the patience.

**Comment by jarallah** [comment]
@Matthewrbowker  Did you find a solution?

**Comment by Matthewrbowker** [comment]
Not yet, though I am looking.  

As of right now https://tools.wmflabs.org/xtools-ec/?user=%D8%AC%D8%A7%D8%B1+%D8%A7%D9%84%D9%84%D9%87&project=ar.wikipedia.org is showing 39,456

https://tools.wmflabs.org/xtools/sc/?user=%D8%AC%D8%A7%D8%B1+%D8%A7%D9%84%D9%84%D9%87&project=ar.wikipedia.org is showing 39,462 .  The Simple Edit Counter is just a simple count query, so I'm inclined to trust it more.

Appears to be a math error somewhere.  I'll keep digging more, though the discrepancy is now 7 edits as opposed to thousands.

**Comment by Matthewrbowker** [comment]
Slight tangent: The development version of xtools is returning the same results, but it's different from both of the above links.  

http://xtools-dev.wmflabs.org/sc/arwiki/%D8%AC%D8%A7%D8%B1%20%D8%A7%D9%84%D9%84%D9%87

http://xtools-dev.wmflabs.org/ec/arwiki/%D8%AC%D8%A7%D8%B1%20%D8%A7%D9%84%D9%84%D9%87

**Comment by jarallah** [comment]
This Link http://xtools-dev.wmflabs.org/ec/arwiki/%D8%AC%D8%A7%D8%B1%20%D8%A7%D9%84%D9%84%D9%87 Is Not True My Edits In Enwiki Is 47 Only But In The link my edits in Enwiki is 9,055 and in Commonswiki and other wiki also mistaken.

but this http://xtools-dev.wmflabs.org/sc/arwiki/%D8%AC%D8%A7%D8%B1%20%D8%A7%D9%84%D9%84%D9%87 The difference only 49 edits with my Total Edits:    39,509. is there another user has the same issue.

**Comment by Matthewrbowker** [comment]
http://xtools-dev.wmflabs.org/ec/arwiki/%D8%AC%D8%A7%D8%B1%20%D8%A7%D9%84%D9%84%D9%87 - Yes, the edit counter is not processing data right now because I'm still writing it.  The number I'm checking is in the top left - that's the only portion of the page that's working right now.  Does that number match?

That's good to hear - only 49 off.  Closer!

**Comment by Matthewrbowker** [comment]
Hello!  I am going to close this, as we've had extensive discussion about the discrepancy.  What is boils down to is a difference between the way MediaWiki and XTools count edits.  MediaWiki has access to data that XTools does not.  If you want to read it, our discussion is at https://phabricator.wikimedia.org/T163284
