### ISSUE TITLE
Overwriting of redirects shouldn't be included in AdminStats

### ISSUE THREAD

**Issue by sjoerddebruin** [x-tools/xtools-legacy#105]
Overwriting a redirect creates a entry in the deletion log now, causing non-sysops showing up in the AdminStats view ([example](https://tools.wmflabs.org/xtools/adminstats/?project=nl.wikipedia.org&begin=2015-10-01&end=)) Can these be excluded?

**Comment by Matthewrbowker** [comment]
Closing, please contribute at https://phabricator.wikimedia.org/T145677

**Comment by sjoerddebruin** [comment]
Maybe change the bug reporting link in the footer then. :)

**Comment by Matthewrbowker** [comment]
That close was more to centralize the discussion.  Eventually, we're going to move all the bugs to one place, but not yet.
