### ISSUE TITLE
AdminStats: Non-admins can add deletion log entries by moving over a page

### ISSUE THREAD

**Issue by Sky2042** [x-tools/xtools-legacy#106]
Moving over a page now causes non-admins to be added to the deletion log as a the deleting entity. For example, I appear on en.WP adminstats even though I am not an admin (ref user "Izno").

It appears that the count on AdminStats is not getting adminstats for only admins, but instead counting all deletion log entries. I don't know if this is desirable.

**Comment by Matthewrbowker** [comment]
https://phabricator.wikimedia.org/T145677

Please comment there to keep the discussion central.
