### ISSUE TITLE
Total bytes of editing

### ISSUE THREAD

**Issue by davidhedlund** [x-tools/xtools-legacy#107]
https://en.wikipedia.org/w/Wikipedia:WikiProject_Medicine/Stats/Top_English_medical_editors_2013b lists:
* Changed bytes
* Added bytes
* Deleted bytes

Can I list my total edits in bytes (changed bytes + added bytes + deleted bytes), I cannot find anything about it on this link for example: https://tools.wmflabs.org/xtools-ec/?user=%20Cyberpower678&lang=en&wiki=wikipedia.

The current text is "Total edits" is bolded at the page provided by the link above, but my opinion is that "Total edited bytes" is far more relevant, but both should be listed.

In the "Top edits" page it is not possible to use regular expressions (eg asterisk) for "Page title:", example: https://tools.wmflabs.org/xtools/topedits/?user=Cyberpower678&project=en.wikipedia.org&namespace=0&article=*

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by samwilson** [comment]
> In the "Top edits" page it is not possible to use regular expressions (eg asterisk) for "Page title:", example: https://tools.wmflabs.org/xtools/topedits/?user=Cyberpower678&project=en.wikipedia.org&namespace=0&article=*

The namespace view of topedits already includes all articles (i.e. `*`). Or is the idea here to add actual regex support, e.g. `List of Pokémon: .*` to get only those articles?

**Comment by davidhedlund** [comment]
@samwilson 
> is the idea here to add actual regex support, e.g. List of Pokémon: .* to get only those articles?

Yes.

**Comment by davidhedlund** [comment]
@samwilson Feel free to file a separate issue for that if you think its best.

**Comment by Matthewrbowker** [comment]
Hi, @davidhedlund 

We are moving over to the Wikimedia Foundation Phabricator for development of XTools. I've migrated your task there, you are welcome to watch it at https://phabricator.wikimedia.org/T172001

**Comment by davidhedlund** [comment]
@Matthewrbowker Thank you.
