### ISSUE TITLE
Xtools for non-wikimedia wikis

### ISSUE THREAD

**Issue by ferdi2005** [x-tools/xtools-legacy#109]
How can I adapt Xtools for **non-wikimedia** wikis like [this](http://www.wikigram.it).
I can host it on my server, but I need help for adapting.
Sorry for my poor English.
Regards and Thanks

**Comment by cyberpower678** [comment]
You can’t.  It’s too environment specific at the moment to move it anywhere else.  Also you need access to the wiki DBs to use it.  Sorry.

**Comment by ferdi2005** [comment]
I have access to the Wiki's db

**Comment by Matthewrbowker** [comment]
Hello! I am working on making xTools work on other wikis, as part of the rewrite process. Please watch this ticket, I'll post a comment when it's done. 

The reason it won't work right now is that xTools relies on the Tool Labs functionality. Not just the databases, but the grid engine and the directory structure as well.

**Comment by ferdi2005** [comment]
Thanks @Matthewrbowker

**Comment by Matthewrbowker** [comment]
@ferdi2005 Our rewrite has entered beta.  If you're interested, see http://github.com/x-tools/xtools under "releases"
