### ISSUE TITLE
Don't use flash for charts/graphs

### ISSUE THREAD

**Issue by bymerej** [x-tools/xtools-legacy#11]
(well really don't use flash. but this issue is about charts/graphs)

e.g. at https://tools.wmflabs.org/xtools/articleinfo/index.php?article=Hampton,_Florida&lang=en&wiki=wikipedia

options:
- http://simile-widgets.org/timeplot/
- steal something from limn

**Comment by bymerej** [comment]
pipe dream: get structured data about important events related to articles and optionally plot them too. e.g. for a person or company you could plot events in the life of that person/company.

less useful for subjects which are purely historical (the article's not evolving contemperaneously with the subject's evolution. [[Barack Obama]] is still doing new notable things, [[Abraham Lincoln]] is not) In some cases activity around the time of a major anniversary might be interesting. e.g. 400th anniversary of the [[Hudson River]]

see "google trends" displaying news articles for inspiration

**Comment by Hedonil** [comment]
Thanks for the good suggestions about DHTML & AJAX components!
For now, all flash components have been removed, replaced by non-JS vanilla chart graph.
