### ISSUE TITLE
Tool shows bad entries

### ISSUE THREAD

**Issue by urbanecm** [x-tools/xtools-legacy#110]
Hi, this tools shows bad entries, see https://tools.wmflabs.org/xtools-ec/?user=Luk%C3%A1%C5%A1+Kr%C3%A1l&project=cs.wikipedia.org (he didn't made 92 % edits without summary, I checked it using labs database). 

And for my account (https://tools.wmflabs.org/xtools-ec/?user=Martin+Urbanec&project=cs.wikipedia.org) it does not show anything at all. 

Please fix it soon!

**Comment by MusikAnimal** [comment]
@urbanecm Perhaps you're misreading? I see 2,568 edits **with summary** (not without), out of 2,898 total edits. I also see a full report for your account. The service may have been down when you last checked. Is it working for you now?

**Comment by urbanecm** [comment]
This is because I'm Czech I think. I see bez shrnutí: 92%, se shrnutím: 8 %ˇ. Translated into Englush, 92 % without summary, 8 % with summary. Seems this is only mistranslation. 

For my account it works with the same mistake (99,7% bez shrnutí, 0,3% se shrnutím, in English 99,7% without summary, 0,3 % with summary).

**Comment by MusikAnimal** [comment]
Aha! I think I have fixed it at translatewiki.net. It might take take a while to get backported into the tool, and for the cache to be cleared. Thanks for the report!

**Comment by urbanecm** [comment]
Thank you!

**Comment by Matthewrbowker** [comment]
@MusikAnimal Any update on this?  Has the new translation landed?

**Comment by urbanecm** [comment]
Yes, they are loaded @Matthewrbowker. Closing then and thanking all involved.
