### ISSUE TITLE
articleinfo tool has a 404

### ISSUE THREAD

**Issue by gerardduenas** [x-tools/xtools-legacy#111]
The embedding of the assessment section seems to be broken.
![captura de pantalla de 2016-12-09 10 33 39](https://cloud.githubusercontent.com/assets/10157199/21044205/0cbb1a2c-bdfb-11e6-836a-56b8f4226ca6.png)

**Comment by Matthewrbowker** [comment]
Can you please give the URL that you were attempting to load?

**Comment by gerardduenas** [comment]
https://tools.wmflabs.org/xtools-articleinfo/?article=F-86+Sabre&project=ca.wikipedia.org

**Comment by cyberpower678** [comment]
It looks like you were trying to load something different in the screenshot, completely unrelated to xtools according to the echoed back URI

**Comment by Matthewrbowker** [comment]
@cyberpower678 I get what he means.  We are loading a page from another tool within articleinfo.  Therefore it is an xtools problem.  I will troubleshoot this evening.

**Comment by gerardduenas** [comment]
Sorry if I didn't explain myself, but you've got what I meant. Thanks guys for the great job you do developing this tool!

**Comment by cyberpower678** [comment]
Matthew is the one to thank.  I’ve passed on the crown of lead maintainer to him.  He does extraordinary work for xTools.

**Comment by Matthewrbowker** [comment]
Fixed on the live tool.  The box will now be empty for every wiki except for the English Wikipedia.  See #112 for the code fix I applied.  Thank you for the report!
