### ISSUE TITLE
Blank Result

### ISSUE THREAD

**Issue by JustBerry** [x-tools/xtools-legacy#113]
https://tools.wmflabs.org/xtools-ec/?user=MrLinkinPark333&project=en.wikipedia.org

**Comment by JustBerry** [comment]
Odd--works now...

**Comment by Matthewrbowker** [comment]
We are tracking this issue at https://phabricator.wikimedia.org/T97153 (if it's the same one I think it is), it happens when the database server goes away before fully creating the temporary table.
