### ISSUE TITLE
Wikipedia Xtools

### ISSUE THREAD

**Issue by bronhiggs** [x-tools/xtools-legacy#114]
I am currently using Wikipedia and have been experiencing difficulties with one of the X-tools for the past week.  I have been informed by WP's technical department that this is an external service and asked to report the problem here.
The details are:
At the top of my screen is a link to "Contributions". If I click on this and then click on "Edit Count" and then click at the bottom of the screen, I get a list of pages that I have contributed to (See: https://tools.wmflabs.org/xtools-ec/?user=BronHiggs&project=en.wikipedia.org.) In the past, I was able to click on the "page history" of an article of interest, and get a neat summary of a page's edit history. For the past week or so, this function has been working erratically - sometimes on and sometimes off and at other times has directed me to a form (See, for example, https://tools.wmflabs.org/xtools-articleinfo/?lang=en&wiki=wikipedia&page=Advertising_management) which I have not seen before and which, if used, also returns the error message "no revisions found". Over the past four days, this application has not been working at all. After waiting an inordinately long period of time (several minutes), I see a message that says "no revisions to show". The net result is that I have not been able to get a positive result or view any page history. I have only been on Wikipedia for three months, but in that time, this application has worked seamlessly. It has only been in the past week that I have experienced difficulties. Nothing else has changed. I am not using a different browser or operating system and have not changed any of my settings.

Thank-you 
Bronhiggs

**Comment by Matthewrbowker** [comment]
I'll take a look this evening, page logs should reveal something.

**Comment by bronhiggs** [comment]
Great, thanks

I'll have a look for it in the morning. (I am on Australian time, so it's evening here now and I'll be off to bed before too long!)

Regards
Bronwyn Higgs
--------------------------------------------
On Mon, 23/1/17, Matthew Bowker <notifications@github.com> wrote:

 Subject: Re: [x-tools/xtools] Wikipedia Xtools (#114)
 To: "x-tools/xtools" <xtools@noreply.github.com>
 Cc: "bronhiggs" <Cooljazz@y7mail.com>, "Author" <author@noreply.github.com>
 Received: Monday, 23 January, 2017, 12:28 PM
 
 I'll take a look this
 evening, page logs should reveal something.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by Matthewrbowker** [comment]
I am unable to reproduce this issue, I'm not seeing it.

There are some log entries that read like so:

> 2017-01-23 01:49:52: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  mysqli::close(): Couldn't fetch mysqli in /data/project/xtools/modules/WebTool.php on line 1161
> 2017-01-23 01:49:52: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  mysqli::close(): Couldn't fetch mysqli in /data/project/xtools/modules/WebTool.php on line 1161
> 2017-01-23 01:49:52: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  parse_ini_file(/data/project/xtools/replica.my.cnf): failed to open stream: Permission denied in /data/project/xtools/modules/WebTool.php on line 582
> 2017-01-23 01:49:52: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  mysqli::mysqli(): (HY000/1045): Access denied for user ''@'10.68.21.13' (using password: NO) in /data/project/xtools/modules/WebTool.php on line 1135
> 2017-01-23 01:49:52: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  mysqli::set_charset(): Couldn't fetch mysqli in /data/project/xtools/modules/WebTool.php on line 1136
> 2017-01-23 01:49:53: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  mysqli::close(): Couldn't fetch mysqli in /data/project/xtools/modules/WebTool.php on line 1161

Appears our replica.my.cnf file had to be recreated.

Please comment when you encounter the issue again, I can use the timestamp to check the error logs.

**Comment by Matthewrbowker** [comment]
Never mind, I just ran into it.  There is no output in the logs.  I'll put some debugging code into article info and attempt to reproduce.  Apologies about that.

**Comment by summermielke** [comment]
It seems to be working for me now. Thank you!

Does anyone know if there is a way to see which Wikipedia pages have the most edits done by bots?

**Comment by bronhiggs** [comment]
Yes, thanks
It is working for me too.


--------------------------------------------
On Fri, 3/2/17, summermielke <notifications@github.com> wrote:

 Subject: Re: [x-tools/xtools] Wikipedia Xtools (#114)
 To: "x-tools/xtools" <xtools@noreply.github.com>
 Cc: "bronhiggs" <Cooljazz@y7mail.com>, "Author" <author@noreply.github.com>
 Received: Friday, 3 February, 2017, 9:26 AM
 
 It seems to be working for me
 now. Thank you!
 Does anyone know if there is a way to see which Wikipedia
 pages have the most edits done by bots?
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by MusikAnimal** [comment]
Alrighty then... just as last time, the magic XTools fairies came along and fixed it for us... we didn't have to do anything! FYI a complete rewrite is in the near future that should be significantly more stable and at least more maintainable, such that if issues like this come up we'll at least have a clue as to what went wrong and how to fix it.
