### ISSUE TITLE
blame don't give correct link

### ISSUE THREAD

**Issue by xcombelle** [x-tools/xtools-legacy#117]
I did this search

http://tools.wmflabs.org/xtools/blame/?project=fr.wikipedia.org&article=Discussion%3ALa+Manif+pour+tous&text=http%3A%2F%2Fcdn.bvoltaire.fr%2Fmedia%2F2012%2F12%2Fpedophilie-565x668.jpeg

It should return this link https://fr.wikipedia.org/w/index.php?title=Discussion%3ALa_Manif_pour_tous&diff=prev&oldid=103630151

and return this one 

http://fr.wikipedia.org/w/index.php?title=Discussion%3ALa_Manif_pour_tous&diff=prev&oldid=125064444

Actually it previously worked because it was the way I found the first link.

**Comment by MusikAnimal** [comment]
Yes I can say from experience this tool is not really reliable. We'll likely rewrite this from scratch in the new version of XTools, and will be sure to do thorough testing to ensure accuracy. The new version should be out sometime in 2017, hopefully within 3-6 months.

**Comment by Matthewrbowker** [comment]
We have decided not to include blame in the new version of XTools as of launch.  Closing this task.
