### ISSUE TITLE
Not Working for sa.wikipedia.org

### ISSUE THREAD

**Issue by NehalDaveND** [x-tools/xtools-legacy#118]
https://tools.wmflabs.org/xtools-ec/index.php?user=NehalDaveND&project=sa.wikipedia.org&uselang=sa

**Comment by Matthewrbowker** [comment]
I'll take a look at this.

**Comment by MusikAnimal** [comment]
Working for me. Perhaps you fixed it @Matthewrbowker ?

**Comment by Matthewrbowker** [comment]
@MusikAnimal Not working for me.

> Notice: Undefined variable: dbNameIn in /data/project/xtools/modules/WebTool.php on line 604
> 
> Fatal error: Call to a member function msg() on null in /data/project/xtools/modules/WebTool.php on line 671

Related to my fix for #85

**Comment by Matthewrbowker** [comment]
Appears to be working now (had a variable typo).  Can anyone confirm?
