### ISSUE TITLE
Edit count gets date of first edit wrong for long-time editors

### ISSUE THREAD

**Issue by stuartyeates** [x-tools/xtools-legacy#119]
https://tools.wmflabs.org/xtools-ec/?user=Stuartyeates&project=en.wikipedia.org has my first edit as "Dec 31, 2099, 12:00 AM" which is clearly wrong. I was expecting a date about 13 years ago.

**Comment by stuartyeates** [comment]
So this looks like a transient (possibly cached) error that occurs when the variable "$mFirstEdit" in /modules/Counter.php remains in an uninitialised state (the 2099 value is the in-line initialised value and somehow it's not getting the real data from the database). could that be caught and handled a little better please?

**Comment by Matthewrbowker** [comment]
See https://phabricator.wikimedia.org/T97153 .  

This is definitely something that needs to be handled better in the rebirth.  @samwilson is that part of your plan for the edit counter?

**Comment by samwilson** [comment]
Yes, this is working in my branch of the rebirth; the 'first edit' date is the earliest date of any revision or archived-revision for a given user. Same idea for the last-edit date.

**Comment by Matthewrbowker** [comment]
Hello, we just pushed a beta of the new XTools.  It appears to be working there, so I'm closing this task.  See https://xtools.wmflabs.org/ec/en.wikipedia.org/Stuartyeates
