### ISSUE TITLE
¿A easy API for bots?

### ISSUE THREAD

**Issue by KernelFreeze** [x-tools/xtools-legacy#12]
Hello, How to connect a bot to the edit counter with a simple api?
Sorry for the bad english, I'm Colombian :)

**Comment by JackPotte** [comment]
Hola, currently you can only use the URL to get the result in HTML, ex:
http://tools.wmflabs.org/xtools/pcount/index.php?name=JackPotte&lang=fr&wiki=wikibooks
Three inputs:
1) name
2) lang
3) wiki
Many outputs in a table depending on "lang":
&#60;tr &#62;&#60;td  style="border: 1px solid #000;background:#FF5555;" &#62;Principal&#60;/td&#62;&#60;td &#62;6979&#60;/td&#62;&#60;td &#62;85.55%&#60;/td&#62;&#60;/tr&#62;

**Comment by cyberpower678** [comment]
That's not true.  https://tools.wmflabs.org/pcount/api.php

**Comment by cyberpower678** [comment]
Sorry.  I meant https://tools.wmflabs.org/xtools/pcount/api.php

**Comment by JackPotte** [comment]
Yes but this page doesn't provide the details per namespace: https://tools.wmflabs.org/xtools/pcount/api.php?name=JackPotte&lang=fr&wiki=wikibooks

**Comment by cyberpower678** [comment]
There was no request to have it put in?  Besides I don't see why a bot would need that.

**Comment by KernelFreeze** [comment]
Thanks, but I need a details per namespace in the API for run a vote checker bot, using the namespace Main (0) and "Anexo" (104), if you help me with this, I thank them for ever.

**Comment by JackPotte** [comment]
I can't do that today because the require_once( '/data/project/xtools/database.inc'); doesn't work with this clone (the file isn't in the repository). So I would be obliged to debug from the Wikimedia server, in a new project (eg: preprod_xtools).

**Comment by KernelFreeze** [comment]
No solution?

**Comment by cyberpower678** [comment]
It can't be done that quickly. :p

**Comment by cyberpower678** [comment]
Hi.  There is a new API available that should help you with your needs.  It's very fast and reliable.

https://tools.wmflabs.org/supercount/api.php
