### ISSUE TITLE
Add option for deleted pages

### ISSUE THREAD

**Issue by davidhedlund** [x-tools/xtools-legacy#120]
Can you please add a new drop down menu for with title **Deleted pages** in this [form](https://tools.wmflabs.org/xtools/pages/)?

**Deleted articles** should have these options:
* Include deleted and created pages
* Include created pages only
* Exclude created pages

I don't think its convenient to read the full list if I just want to know what I actually achieved.

**Comment by MusikAnimal** [comment]
You can hide redirects by selecting "Exclude redirects" in the [form](https://tools.wmflabs.org/xtools/pages/). E.g. see [here](https://tools.wmflabs.org/xtools/pages/?user=David%20Hedlund&lang=en&wiki=wikipedia&namespace=0&redirects=noredirects&limit=1000). There is no option to hide deleted pages, but we can add that to the new XTools which should be deployed this quarter.

**Comment by davidhedlund** [comment]
@MusikAnimal Thanks. I updated the title and text.

**Comment by Matthewrbowker** [comment]
Hi, @davidhedlund 

We are moving over to the Wikimedia Foundation Phabricator for development of XTools. I've migrated your task there, you are welcome to watch it at https://phabricator.wikimedia.org/T172003

**Comment by davidhedlund** [comment]
@Matthewrbowker I subscribed to it on Phabricator as I did with all other issues that you migrated. Thank you.
