### ISSUE TITLE
Add "TOP added text" page

### ISSUE THREAD

**Issue by davidhedlund** [x-tools/xtools-legacy#121]
* We have [TOP edits](https://tools.wmflabs.org/xtools/topedits/) that lists all top pages by number of edits.
* For articles there are "TOP 10 by added text", [example](https://tools.wmflabs.org/xtools-articleinfo/?article=Alcoholic+drink&project=en.wikipedia.org&editorlimit=10#topeditors). But there are no "TOP added text" page that lists all articles automatically like with "TOP edits" -- Can you please add it?

**Comment by Matthewrbowker** [comment]
I really like this idea actually.  Maybe we can roll it into the new topedits? @samwilson it appears you added this tool to rebirth.

**Comment by davidhedlund** [comment]
> Maybe we can roll it into the new topedits?

Smart.

**Comment by Matthewrbowker** [comment]
Hi, @davidhedlund 

We are moving over to the Wikimedia Foundation Phabricator for development of XTools. I've migrated your task there, you are welcome to watch it at https://phabricator.wikimedia.org/T172006

**Comment by davidhedlund** [comment]
@Matthewrbowker Thank you again.
