### ISSUE TITLE
Commons ("commonswiki") links give an error

### ISSUE THREAD

**Issue by jc86035** [x-tools/xtools-legacy#122]
[This link](https://tools.wmflabs.org/xtools-ec/?user=Jimbo+Wales&project=commonswiki) doesn't work and returns "wt::getUserInfo is not a valid wiki", whereas [this link](https://tools.wmflabs.org/xtools-ec/?user=Jimbo+Wales&project=commons) does. The former is linked to from the "SUL editcounter (approximate)" column in the second subsection of the "General statistics" section on user stats pages for other wikis.

**Comment by Matthewrbowker** [comment]
#101
