### ISSUE TITLE
Not recognising User:It's gonna be awesome

### ISSUE THREAD

**Issue by Cabayi** [x-tools/xtools-legacy#123]
Running the tools on  User:It's gonna be awesome  causes them to barf...

User ID:	
User groups:	
First edit:	Dec 31, 2099, 12:00 AM
Latest edit:	Dec 2, 2, 12:00 AM

https://tools.wmflabs.org/xtools-ec/?user=It%27s+gonna+be+awesome&project=en.wikipedia.org

**Comment by MusikAnimal** [comment]
Looks like it's working for me? The edit counter goes down occasionally, maybe you just had bad timing. The new Xtools will be fully stable without nasty barfs like this :) It should be released in a month or two, if not sooner. Stay tuned!

**Comment by Matthewrbowker** [comment]
Works for me as well.
