### ISSUE TITLE
Incorrect results - non admins

### ISSUE THREAD

**Issue by eranroz** [x-tools/xtools-legacy#124]
(reported in hewiki - moving it here)
The tool reports wrong statistics for example:
http://tools.wmflabs.org/xtools/adminstats/?project=he.wikipedia.org&begin=2017-02-16&end=

* It shows users who aren't and weren't admins in the past. (example: Sokuya)
* It seems that those users, did some delete actions as part of pagemove.

**Comment by Matthewrbowker** [comment]
https://phabricator.wikimedia.org/T154408
