### ISSUE TITLE
sa.wikipedia

### ISSUE THREAD

**Issue by NehalDaveND** [x-tools/xtools-legacy#126]
I can't see..

https://tools.wmflabs.org/xtools-ec/index.php?user=NehalDaveND&project=sa.wikipedia.org&uselang=sa

Please help

**Comment by samwilson** [comment]
This is being fixed in the rewrite of XTools. I'll check now to see if it's working there yet....

**Comment by samwilson** [comment]
This is functional in the new version; see http://tools.wmflabs.org/xtools-dev/ec/sa.wikipedia.org/NehalDaveND
