### ISSUE TITLE
[articleinfo] Wrong assumption regarding deleted text

### ISSUE THREAD

**Issue by Ltrlg** [x-tools/xtools-legacy#127]
When an article has no edit removing text (in terms of byte count), articleinfo still shows the “Max. text deleted” field, with a red positive number, assuming the lowest value must be a deletion. See for example [wikt:fr:Thésaurus:concert/français](https://tools.wmflabs.org/xtools-articleinfo/index.php?project=fr.wiktionary.org&article=Th%C3%A9saurus:concert/fran%C3%A7ais&uselang=en).

**Comment by MusikAnimal** [comment]
Nice catch! I will make sure this is fixed in the new version of XTools, which we hope to have released by July. Thanks

**Comment by MusikAnimal** [comment]
I can confirm this has been fixed in the rewrite. Closing this issue as we are officially no longer supporting the legacy XTools. As I said the new version should be out very soon. Get excited! :)

**Comment by Ltrlg** [comment]
Many thanks!
