### ISSUE TITLE
Oauth doesn't work

### ISSUE THREAD

**Issue by ferdi2005** [x-tools/xtools-legacy#128]
Oauth with it.wikipedia doesn't work.
Oauth with metawiki redirect to the tool without the project url and the auth fails. Sorry for poor English

**Comment by samwilson** [comment]
Can you please test with the new test site: https://xtools-dev.wmflabs.org/ and see if your problem is resolved there.

**Comment by samwilson** [comment]
Oauth is now working in the new XTools. See https://xtools.wmflabs.org/

Please do open a new issue on Phabricator if you're still having problems.
