### ISSUE TITLE
pcount is 404

### ISSUE THREAD

**Issue by 1ec5** [x-tools/xtools-legacy#14]
[pcount](https://tools.wmflabs.org/xtools/pcount/) gives an HTTP 404 error.

**Comment by nemobis** [comment]
Wasn't it disabled on purpose because it kept going down for overload?

**Comment by 1ec5** [comment]
Oh, I didn’t know that. I filed this bug because of complaints that it wasn’t working from the Vietnamese Wikipedia’s Special:Contributions footer. In any case, I’ve synchronized that footer with the English Wikipedia version, which links to the [User Analysis Tool](https://tools.wmflabs.org/supercount/) instead.

**Comment by stwalkerster** [comment]
If it has been taken down, it should probably redirect to a working tool
instead (if permanent), or at least state what's happened to it (with a
link to a working tool).

If it is hitting resources too hard, maybe we should get some data on what
part is resource intensive and optimise/cache/make optional/ratelimit as
appropriate.

**Comment by cyberpower678** [comment]
Err.  It looks Iike I accidentally destroyed the redirect.

Gesendet von Maximilian's iPhone. 
(Sent from Maximilian's iPhone.)

**Comment by cyberpower678** [comment]
Fixed
