### ISSUE TITLE
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

### ISSUE THREAD

**Issue by nemobis** [x-tools/xtools-legacy#17]
http://tools.wmflabs.org/xtools/editsummary/index.php?name=Magnus_Manske&lang=www&wiki=wikidata (same for www.wikisource.org).

Language wikis work, as well as http://tools.wmflabs.org/xtools/editsummary/index.php?name=Nemo_bis&lang=www&wiki=mediawiki . Some missing domain -> DB name mapping I guess.

**Comment by cyberpower678** [comment]
Meh.  I'm merging this into the user analysis tool.

**Comment by cyberpower678** [comment]
The user analysis tool handles those issues very well.

**Comment by Hedonil** [comment]
fixed
