### ISSUE TITLE
Page created by an user show always page created on wikipedia family, family selection broken

### ISSUE THREAD

**Issue by phil-el** [x-tools/xtools-legacy#19]
The family selection doesn't work http://tools.wmflabs.org/xtools/pages/?user=Phe&lang=fr&wiki=wikisource&namespace=all&redirects=none , the family selection show correctly the namespace of http://fr.wikisource.org but page creation are mine for http://fr.wikipedia.org not wikisource

**Comment by Hedonil** [comment]
fixed
