### ISSUE TITLE
Warning: [MessagesFunctions::parse] Problems when parsing the message

### ISSUE THREAD

**Issue by nullzero** [x-tools/xtools-legacy#20]
When accessing http://tools.wmflabs.org/xtools/articleinfo/index.php?article=Sultanate_of_Singora&lang=en&wiki=wikipedia, I encountered the following error: 

> Warning: [MessagesFunctions::parse] Problems when parsing the message. For Information see below!.
> Fatal error: [MessagesFunctions::plural] Invalid number argument to {{PLURAL: ...}} in /data/project/intuition/src/Intuition/language/MessagesFunctions.php on line 123.

**Comment by nullzero** [comment]
Actually, it happens with every article.

**Comment by Hedonil** [comment]
Sorry for that! I was working on I18 integration on another part of Xtools and didn't notice the error. Fixed it by suppressing fatal errors from intuition categorically and modified the causing message.
