### ISSUE TITLE
Wiki fields should be overriden if defined in the $_GET parameters

### ISSUE THREAD

**Issue by cyberpower678** [x-tools/xtools-legacy#21]
For example, the current default is en and wikipedia.  However if $_GET['wiki'] is defined, it should override that value, and the textboxes should en and what ever values $_GET['wiki'] is.  Same for lang

**Comment by Hedonil** [comment]
Yep. It's temporarily fixed default en/wikipedia. The new defaults are coupled with pre-settings you mentioned and new I18n-language settings (either browser default accept lang or manually set gui language).
I hope to finish this I18-thingy this weekend.

**Comment by Hedonil** [comment]
Setting are in place now.
