### ISSUE TITLE
Error 500 on 0 edits accounts

### ISSUE THREAD

**Issue by nemobis** [x-tools/xtools-legacy#22]
https://meta.wikimedia.org/wiki/Special:CentralAuth/Thomas_it account exists -> https://tools.wmflabs.org/xtools/ec/?user=Thomas+it&lang=it&wiki=wikipedia but gives internal error

**Comment by Hedonil** [comment]
Strange guy, indeed ;). I tried...
https://tools.wmflabs.org/guc/?user=Thomas+it   -> nothing
https://meta.wikimedia.org/w/index.php?title=Special:CentralAuth&target=Thomas+it  ->exits, but no counts
MariaDB [itwiki_p]> select count(_) from revision_userindex where rev_user_text = 'Thomas it';
+----------+
| count(_) |
+----------+
|        0 |
+----------+
1 row in set (0.01 sec)

So, nothing to see.
At least, now you get a form with his userid, and no error.

**Comment by Hedonil** [comment]
It seems the '*'<-'star sign'  has been swallowed up in the output above....

**Comment by cyberpower678** [comment]
@Hedonil You get a trout for using rev_user_text instead of rev_user for registered users.

**Comment by Hedonil** [comment]
Hehe, just for the quickie check. As you stated: Pro's _always_ use rev_user for prod. purposes :P

**Comment by cyberpower678** [comment]
Yep. :p

**Comment by Hedonil** [comment]
fixed.
