### ISSUE TITLE
Range contributions: results by time

### ISSUE THREAD

**Issue by Spinningspark** [x-tools/xtools-legacy#23]
Would it be possible to have a switch in the url to display only results by time, or to put results by time first.  This is the most useful part of the data as far as identifying IP hopping disruption goes and it would save a lot of scrolling if this was placed first, or at least immediately after the short table of basic information.

**Comment by Spinningspark** [comment]
Also, just simply the last N results by time from the whole range, rather than the last n from each IP would be good.  It is usually the most recent activity that is of interest.

**Comment by Hedonil** [comment]
Switched the 'by time' section to the top of the result.
