### ISSUE TITLE
Some pages can't been found when using “Page history” with the wiki project which used the Automatic conversion

### ISSUE THREAD

**Issue by Cwek** [x-tools/xtools-legacy#24]
I come from zh.wp.

When I use “Page history” to check the page with converted name ,such as "刀剑神域",it will return a error which is "No revisions found ".But If check the page with real name
, such as "刀劍神域",it will return correct information."刀剑神域" is equal of "刀劍神域".

Maybe the function to get page title isn't friendly for the wiki project which used the Automatic conversion.So I hope it can be fixed.Thanks you for help.

Some Information maybe is helpful.
1. https://meta.wikimedia.org/wiki/Automatic_conversion_between_simplified_and_traditional_Chinese
2. In Mediawiki API,When it's 'action=query',the parameter "converttitles" will make the parameter "titles" change to the page of original name.

**Comment by Hedonil** [comment]
Hi Cwek, very interesting issue! and thanks for the report _and_ the solution.
I've now added "converttitles" attribute to the api queries in Page history module and will look in other modules, too.

**Comment by Cwek** [comment]
It seems working,Thank you for help.
