### ISSUE TITLE
a follow problem with "Page History"

### ISSUE THREAD

**Issue by Cwek** [x-tools/xtools-legacy#26]
Thank you for issue #24 .
But it's intrensting that Some pages with real name also can't check which Maybe it's not the problem of the Automatic conversion, such as "Wikipedia:互助客栈/消息" in zh.wp(real name, with conversion system), "ソードアート・オンライン" in ja.wp ( real name, no conversion system). I can't understand what the hell happened.

A solution which it‘s from your xtool.js is maybe good for the problem, which it's search the pageid of the page first.
Using MediaWiki API, the action parameter is "query", the titles parameter is the page name. Which I am not sure that if the wiki has used the Automatic conversion, the result which it's "action=quuery&meta=siteinfo&siprop=general" will have <variants>'s list in the <general> tag. Beacause of  this,we can add the converttitles parameter if the wiki has the Automatic conversion. From the query, We can get the pageid of what we check the page name.Using the pageid as the page's identity to find the info about the page in the program.

That's I think about it.

**Comment by Hedonil** [comment]
I was able to reproduce this issue. In all submodules the first step is always to get the page id via API and work with it - to avoid encoding issues.
As of now I was able to track down the problem to a python component (json.dumps), which struggles here over some (few) strange chars in japanese rev_comment. I expect to fix this the next days.

**Comment by Hedonil** [comment]
Fixed.
