### ISSUE TITLE
Fix underlying bugs

### ISSUE THREAD

**Issue by cyberpower678** [x-tools/xtools-legacy#3]
There are various bugs needing fixing.

**Comment by nemobis** [comment]
Like some of those in https://jira.toolserver.org/browse/SOXRED perhaps? Need to migrate them: ask valhalla to transfer them to bugzilla and triage there maybe? Copying the relevant ones here or wherever you work.

**Comment by Hedonil** [comment]
Seems to not apply any longer. At least the old issues.
