### ISSUE TITLE
Contributors and dates listed: error  now (worked well previously)

### ISSUE THREAD

**Issue by Zyephyrus** [x-tools/xtools-legacy#30]
Previously contributors listed in history were the same as contributors listed in x-Tools; but to-day there is a wrong list. Example: I've just created this page: https://fr.wikisource.org/w/index.php?title=Wikisource:Extraits/2014/29&action=history

and x-Tools gives this list of dates and contributors: https://tools.wmflabs.org/xtools/articleinfo/index.php?pageid=1748343&project=fr.wikisource.org&uselang=fr

Is it broken for other people too? It was such a wonderful and precious tool, I look forward to seing it back if it is possible!

**Comment by Hedonil** [comment]
During the validation of the database string, it defaulted to frwiki. Thanks for reporting.
Fixed.
