### ISSUE TITLE
RTL languages

### ISSUE THREAD

**Issue by reza1615** [x-tools/xtools-legacy#32]
For RTL Languges like farsi- arabic-Hebrew please set labels RTL spesialy
monthcounts id=monthcounts should be RTL

**Comment by Hedonil** [comment]
Yeah, rtl it is.. ,) I'm working on it.

**Comment by Matthewrbowker** [comment]
I'm going to close this, as it has been fixed in the rewrite. Since the mainstream xtools will be replaced by this, it will be there soon.
