### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Protonk** [x-tools/xtools-legacy#33]
xtools should list the license it uses on github. It's not required but I suspect (maybe I'm wrong!) xtools is not "all rights reserved", which is how we're forced to treat it in the absence of a license.

**Comment by cyberpower678** [comment]
Well.  For the record, xtools uses a GPL.  I'll add it to xtools shortly.

**Comment by Protonk** [comment]
Thanks!

**Comment by cyberpower678** [comment]
Added.
