### ISSUE TITLE
RfA count creates false positives

### ISSUE THREAD

**Issue by Cookies52** [x-tools/xtools-legacy#37]
Just a bit of feedback on the RfX vote counter. Firstly, a way to reduce false positives would be to ignore the editors own RfX's. For example, with mine (https://tools.wmflabs.org/xtools/rfap/index.php?project=en.wikipedia.org&user=Mdann52), it shows both of mine as "unknown" votes, so it is probably best to ignore anyone's own RfA's in the count. Additionally, ignoring the "/recent" page is also worthwhile.

**Comment by Hedonil** [comment]
Thanks for the feedback. Preparing a patch for that.

**Comment by Cookies52** [comment]
Any progress on this?

**Comment by Matthewrbowker** [comment]
I have implemented these changes in the rewrite, once they are reviewed and implemented you should be able to see them.  Slated for version 3.1.
