### ISSUE TITLE
Can top editors (Top 10 by added text) be accessed using xtools/api.php?

### ISSUE THREAD

**Issue by willbeaufoy** [x-tools/xtools-legacy#38]
I've been using the cool xtools gadget, and wanted to add the top 10 added text field to it so this appears on wikipedia pages together with pageviews / created by etc.

Is this info accessible through the API?

**Comment by Hedonil** [comment]
With pleasure! Gadget is work in progress, many options will be configurable. I'll take this into account.

**Comment by willbeaufoy** [comment]
Oh great. I'll watch this issue then.

**Comment by Matthewrbowker** [comment]
Hi, @willbeaufoy 

We are moving over to the Wikimedia Foundation Phabricator for development of XTools.  I've migrated your task there, you are welcome to watch it at https://phabricator.wikimedia.org/T171991
