### ISSUE TITLE
Mistranslated text in editcounter

### ISSUE THREAD

**Issue by zhaofengli** [x-tools/xtools-legacy#41]
The translated Chinese heading ("罪恶") for the block statistics (under Admin actions) shows in all languages including the English one. Moreover, "罪恶" means "sin" in Chinese, which is quite harsh and may be considered offensive. I'd suggest "封禁" ("block" - consider changing the original text as well) which is neutral. This message is also missing from Translatewiki.

**Comment by Hedonil** [comment]
As answered on the  talk page: This is untranslated by intention.  
Yeah, "过错" (fault, usually small ones) sounds good. I configured this. Thanks.
