### ISSUE TITLE
Activate surface for Hungarian language

### ISSUE THREAD

**Issue by SamatWiki** [x-tools/xtools-legacy#44]
Hi! Your tools are really great, thank you for your work.

I would like to ask you to activate the Hungarian language for the tools. It is only partly localized [1](https://translatewiki.net/w/i.php?title=Special:MessageGroupStats&language=en&group=tsint-xtools&setlang=en), but it is easier to translate if we can see how it looks like. And the motivation is bigger to finalize the translation :)

**Comment by Matthewrbowker** [comment]
We are getting ported over to TranslateWiki.  As a part of that, all strings in XTools will be available for translation.  No additional work needs to be done to "activate" Hungarian.
