### ISSUE TITLE
Malayalam numerals

### ISSUE THREAD

**Issue by praveenp** [x-tools/xtools-legacy#46]
Recently Malayalam translations are included in the tools which is big help for Malayalam users. But if we use Malayalam interface, numbers also change to Malayalam. Malayalam numbers are archaic and no more commonly used. Most people don't even know them (problem eg link: https://tools.wmflabs.org/xtools/ec/?user=Praveenp&project=ml.wikipedia.org&uselang=ml ). Please use English numbers (0,1,2,3,...,9) with Malayalam translations.

**Comment by atdt** [comment]
@Krinkle am I correct in thinking that this should be filed against Intuition, instead?

**Comment by Matthewrbowker** [comment]
Hello, @praveenp has this been fixed in our beta?  It looks like it is to me: https://xtools.wmflabs.org/ec/mlwiki/Praveenp?uselang=ml

**Comment by praveenp** [comment]
Hi,  yes, it looks okay in the given link. Thank you :-)

**Comment by Matthewrbowker** [comment]
Excellent!  Thank you so much.
