### ISSUE TITLE
Avoid LanguageTools in names

### ISSUE THREAD

**Issue by dcondrey** [x-tools/xtools-legacy#47]
**Feature request** Disable checking against LanguageTools rules against names (e.g. names of places, movies, tv shows, etc..)  For example "The    Late Late Show with Craig Ferguson" as well as "Kenny Koala and Cooee the Gum Nut Fairy" are reported as errors on the [Animatronics](https://en.wikipedia.org/wiki/Animatronics) article as referenced here: [X! Tools page check of Animatronics](https://tools.wmflabs.org/languagetool/pageCheck/index?url=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FAnimatronics&lang=en)

I imagine this to be a common occurrence amongst names which could be avoided by avoiding text within quotation marks or some other syntax.

**Comment by Matthewrbowker** [comment]
LanguageTool has been disabled and removed, and has been written out of the xtools rewrite.  Closing.
