### ISSUE TITLE
Xtools down

### ISSUE THREAD

**Issue by DiegoQueiroz** [x-tools/xtools-legacy#48]
Currently, Xtools is not accessible at all.

When I try to access https://tools.wmflabs.org/xtools I get an 504 error: Gateway Time-out from nginx/1.5.0.

The same bug was reported on the Bugzilla: https://bugzilla.wikimedia.org/show_bug.cgi?id=72104

**Comment by ajwest123** [comment]
Xtools is still down.
Now, I'm getting a 404 error.
