### ISSUE TITLE
Blanking EditCounterGlobalOptIn.js should opt out from creating graphs

### ISSUE THREAD

**Issue by geraki** [x-tools/xtools-legacy#50]
I blanked https://meta.wikimedia.org/wiki/User:Geraki/EditCounterGlobalOptIn.js but this didn't stop the generation of graphs in https://tools.wmflabs.org/xtools/ec/?project=el.wikipedia.org&user=Geraki

I'm sure it was working properly in the past but in every case blanking EditCounterGlobalOptIn.js should opt out from creating graphs.

**Comment by samwilson** [comment]
This is working now in the new XTools at https://xtools.wmflabs.org — please try again there, and if you're still having trouble open a new issue on Phabricator. Thanks!

The Opt-in only works for the Monthly counts bar chart and Timecard punch chart (and not any other charts); see https://xtools.readthedocs.io/en/latest/opt-in.html for more information.
