### ISSUE TITLE
Edit counter does not display correct data

### ISSUE THREAD

**Issue by Wolbo** [x-tools/xtools-legacy#51]
The edit counter does not seem to be up to date. It does not show any edits from October 25 until today (October 28). Is this a data source issue as other tools, e.g. User Contribution Search, show the same issue? Will the missing data be added?

**Comment by cyberpower678** [comment]
If other tools are having the same issue, then it’s got something to do with Labs Replication DBs, and there’s nothing I can do about it.

**Comment by Wolbo** [comment]
Do you have someone I can contact regarding the Labs Replication DB who is able to help with this issue? I posted it at Village pump (technical) but no response so far.

**Comment by david-r-edgar** [comment]
Has there been any progress on this issue? Edit counter is apparently not counting any of my edits from October 24 until October 28 (the relevant Special:Contributions page does show them).

**Comment by cyberpower678** [comment]
Have you checked if it's there?  If not, contact User:Coren.

**Comment by flyingclimber** [comment]
Count looks good to me
