### ISSUE TITLE
Pages created list for a user does not show recently created page 

### ISSUE THREAD

**Issue by aymatth2** [x-tools/xtools-legacy#52]
https://tools.wmflabs.org/xtools/pages/?user=Aymatth2&lang=en&wiki=wikipedia&namespace=0&redirects=noredirects is missing five pages started on 26-27 October 2014:

18:12, 27 October 2014 Alessandro Tremignon 
00:45, 27 October 2014 Louise Bodin 
15:13, 26 October 2014 Thomas Phillips Thompson  
14:02, 26 October 2014 Hanna Bieber-Böhm 
01:01, 26 October 2014 Gertrude Guillaume-Schack ‎  

Maybe the tool dropped a batch of updates?

**Comment by atdt** [comment]
Since this was reported over a year ago, I am going to assume that the issue was transient and has since been fixed. Please re-open if you encounter this again.
