### ISSUE TITLE
(Semi-)automated edits (approximate)

### ISSUE THREAD

**Issue by Technical-13** [x-tools/xtools-legacy#53]
Please add a section for wikilove (- which accounts for a large chunk of my User talk: edits by welcoming new users whose accounts I create via ACC using https://en.wikipedia.org/wiki/User:Technical_13/Scripts/ACC_WikiLove.js -).

**Comment by gmugar** [comment]
+1. I see stats for bot edits but it would be great if there were also stats for semi-automated edits from tools like TW and HG when looking at the edit stats for user talk.

**Comment by Matthewrbowker** [comment]
Fixed in x-tools/xtools-rebirth@ea1b968
