### ISSUE TITLE
"The ini file could not be read" shown when trying to log in

### ISSUE THREAD

**Issue by flyingclimber** [x-tools/xtools-legacy#57]
When trying to log in to Xecho i'm seeing a 304 and then being taken to a page that say's

"The ini file could not be read" 

Url: https://tools.wmflabs.org/xtools-articleinfo/index.php?login

**Comment by cyberpower678** [comment]
I've got a rewrite underway for this.

**Comment by flyingclimber** [comment]
How can we help?

**Comment by cyberpower678** [comment]
Nothing you can do on your end.  I'm getting ready to deploy the fix.

**Comment by cyberpower678** [comment]
There we go.  It's fixed now.
