### ISSUE TITLE
Add column for MediaWiki namespace edits to adminstats

### ISSUE THREAD

**Issue by Rillke** [x-tools/xtools-legacy#59]
- https://commons.wikimedia.org/wiki/Commons:Administrators/Inactivity_section/Feb-Mar_2015#Confirm_your_adminship_here
- https://web.archive.org/web/20140408023441/http://toolserver.org/~vvv/adminstats.php?wiki=ptwiki_p&tlimit=3600

**Comment by Matthewrbowker** [comment]
Hi, @Rillke 

We are moving over to the Wikimedia Foundation Phabricator for development of XTools. I've migrated your task there, you are welcome to watch it at https://phabricator.wikimedia.org/T171996
