### ISSUE TITLE
Warning: syntax error, unexpected $end, expecting TC_DOLLAR_CURLY or TC_QUOTED_STRING or '"' in Unknown

### ISSUE THREAD

**Issue by nemobis** [x-tools/xtools-legacy#6]
http://tools.wmflabs.org/xtools/pcount/index.php?name=IncolaBot&lang=it&wiki=wikipedia

Warning: syntax error, unexpected $end, expecting TC_DOLLAR_CURLY or TC_QUOTED_STRING or '"' in Unknown on line 45 in /data/project/xtools/public_html/phptemp/PHPtemp.php on line 75 Warning: array_merge(): Argument #2 is not an array in /data/project/xtools/public_html/phptemp/PHPtemp.php on line 75 Warning: Invalid argument supplied for foreach() in /data/project/xtools/public_html/phptemp/PHPtemp.php on line 79 Warning: syntax error, unexpected $end, expecting TC_DOLLAR_CURLY or TC_QUOTED_STRING or '"' in Unknown on line 45 in /data/project/xtools/public_html/phptemp/PHPtemp.php on line 75 Warning: array_merge(): Argument #2 is not an array in /data/project/xtools/public_html/phptemp/PHPtemp.php on line 75 Warning: Invalid argument supplied for foreach() in /data/project/xtools/public_html/phptemp/PHPtemp.php on line 79
IncolaBot - {#tool#} - Strumenti di X!

**Comment by Hedonil** [comment]
After the rewrite of xtools, this issue is  no longer applicable. thanks.
