### ISSUE TITLE
Wrong translation for the main namespace

### ISSUE THREAD

**Issue by he7d3r** [x-tools/xtools-legacy#60]
For some reason, the tool is showing a translation from other language for the main namespace of Portuguese Wikipedia:
https://tools.wmflabs.org/xtools-ec/?lang=pt&wiki=wikipedia&user=MisterSanderson&uselang=en
"Статија" is not a Portuguese word (is it Macedonian?) and should be replaced by "Artigo".

**Comment by Krinkle** [comment]
Relevant code:

https://github.com/x-Tools/xtools/blob/c8db3cbcee5ad6dab6739aaba217d625b35ffecd/modules/WebTool.php#L339-L361

It looks like it's being cached without taking the user language variable into account. As a result, the user language of the user who first makes a query for a certain domain, gets his translation into the main xtools-ec cache for "getNamespaces" of that domain.

I'd recommend one of two things:
- Insert the "mainspace" label outside of caching. Use some kind of placeholder (e.g. "0"), and then outside the method replace it with the message.
- Fragment the cache key by including the language code of the user language. Simply include `$I18N->getLang()` in the `$hash`.

**Comment by atdt** [comment]
Fixed in #77
