### ISSUE TITLE
Tools don't work for mul.ws

### ISSUE THREAD

**Issue by WikimediaDoug** [x-tools/xtools-legacy#61]
Multilingual Wikisource uses the Second Level domain name wiksource.org.  Tools such as AdminStats and !X edit counter assumes a third level domain name and places a "." in front of "wikisource", thus ".wikisource.org", which is invalid and fails.  Unlike www.mediawiki.org, the third level domain name www.wikisource.org merely redirects to wikisource.org.

**Comment by Matthewrbowker** [comment]
@WikimediaDoug Does this look right? https://tools.wmflabs.org/xtools-ec/?user=Matthewrbowker&project=wikisource.org Or are you reporting a different issue?

For background, I believe I fixed this when I fixed #85

**Comment by Matthewrbowker** [comment]
No response.  Closing this as resolved since it works for me.
