### ISSUE TITLE
accesses old LanguageTool URL

### ISSUE THREAD

**Issue by danielnaber** [x-tools/xtools-legacy#62]
xtools accesses URLs like http://tools.wmflabs.org/languagetool/languagetool/pageCheck/index?lang=en&url=Genealogy_%28Armenian_group%29 (I see that from my logs), but I had to move LanguageTool back to my own server. If you can use URLs outside of Tool Labs, please use the new URL, it's `community.languagetool.org/wikiCheck/` instead of `tools.wmflabs.org/languagetool/`.

**Comment by cyberpower678** [comment]
Why did you move away from toollabs?

**Comment by danielnaber** [comment]
It was impossible to get LanguageTool working there properly, both the command-line tools and the Tomcat frontend needed to be restarted manually several times a week.

**Comment by cyberpower678** [comment]
So why not move to your own project space in labs, like we are with xTools.  There you have total control of everything.

**Comment by danielnaber** [comment]
We have our own server and everything runs fine there. Moving again would be too much work with almost no benefit.

**Comment by Matthewrbowker** [comment]
LanguageTool is no longer a functioning resource: http://forum.languagetool.org/t/shutting-down-wikicheck/1098
