### ISSUE TITLE
adminstats

### ISSUE THREAD

**Issue by UkkoUkko** [x-tools/xtools-legacy#65]
Calculation of percentage "admins without action" seems to be inaccurate. 
246/246 =0.988?
Inaccurate even for any other dates.

de.wikipedia.org
Startdatum: 05.01.2015, 00:00 · (0 Tage)
Log types:  delete, block, protect, import, rights
Current Admins (grp):   246
Admins without action:  246 (98,8%)

Ukko

**Comment by cyberpower678** [comment]
Of course.  Didn't you know that 246/246 = 0.988?  We are working on rewriting the concept of mathematics. :p

**Comment by Matthewrbowker** [comment]
I am unable to reproduce this issue in the new XTools.  Please file a phabricator task if you find it again.
