### ISSUE TITLE
RfX Analysis: extend to other dewiki elections

### ISSUE THREAD

**Issue by se4598** [x-tools/xtools-legacy#66]
(transferred from https://en.wikipedia.org/w/index.php?oldid=662439523#Tool)

Please extend https://tools.wmflabs.org/xtools/rfa/?project=de.wikipedia to the following elections:
- https://de.wikipedia.org/wiki/Wikipedia:Oversightkandidaturen
  - e.g. https://de.wikipedia.org/wiki/Wikipedia:Oversightkandidaturen/Sargoth_3
- https://de.wikipedia.org/wiki/Wikipedia:Checkuser
  - e.g. https://de.wikipedia.org/wiki/Wikipedia:Checkuser/Wahl/September_2014/Filzstift
- https://de.wikipedia.org/wiki/Wikipedia:Schiedsgericht
  - e.g. https://de.wikipedia.org/wiki/Wikipedia:Schiedsgericht/Wahl/Mai_2015/Der_Checkerboy

**Comment by Matthewrbowker** [comment]
Didn't realize this was a duplicate task sorry... This has been implemented per https://phabricator.wikimedia.org/T163444 .
