### ISSUE TITLE
X!'s Tools' "Pages created" HTML output isn't being properly escaped

### ISSUE THREAD

**Issue by mzmcbride** [x-tools/xtools-legacy#67]
https://tools.wmflabs.org/xtools/pages/?user=hello%3Cbig%3E%3Cbig%3E%3Cbig%3Ethere&lang=en&wiki=wikipedia&namespace=0&redirects=&limit=10000

The page source currently contains:

```
<p class='alert alert-danger xt-alert'> Hello<big><big><big>there (wt::getUserInfo) does not exist </p>
```

This should be:

```
<p class='alert alert-danger xt-alert'> Hello&lt;big&gt;&lt;big&gt;&lt;big&gt;there (wt::getUserInfo) does not exist </p>
```

Not sanitizing the HTML output can result in cross-site scripting (XSS) vulnerabilities. Any arbitrary user input needs to be treated as untrusted; the input should be sanitized before being sent to the database and/or, as in this specific case, escaped if being echoed back to the user.

**Comment by atdt** [comment]
Dupe of #58. Fixed in d9dc900c96. Thanks for the report.
