### ISSUE TITLE
articleinfo: "No revisions found" on everything

### ISSUE THREAD

**Issue by SamB** [x-tools/xtools-legacy#69]
Did the recent NFS troubles knock articleinfo out of commission? Its been failing every time I try it for at least some days, probably saying "No revisions found" each time (but I often failed to spot that there even was an error message).

(Also, the redirect through e.g. https://tools.wmflabs.org/xtools/articleinfo/?lang=en&wiki=wikipedia&page=Schulze_method seems kind of slow.  Is that just articleinfo taking a while to fail?)

**Comment by Chealer** [comment]
Same for me since a long time. I cannot remember when it worked.

**Comment by Thibaut120094** [comment]
Same here. https://tools.wmflabs.org/xtools-articleinfo/index.php?project=fr.wikipedia.org&article=Goldorak

**Comment by Technical-13** [comment]
Sorry I didn't get time to work on it this week at all like I planned due to real life. I hope to be able to get it running soon.

**Comment by Guy-Delsaut** [comment]
Could you let us know when the tool will work again.  It was a very useful tool to understand the evolution of the articles and who are the authors. I hope it will be available again soon.

**Comment by atdt** [comment]
@Guy-Delsaut it should work now. It was fixed in 4671a2ef9e.
