### ISSUE TITLE
Update homepage or top bar to link all tools

### ISSUE THREAD

**Issue by nemobis** [x-tools/xtools-legacy#7]
Currently the home redirects to pcount and the top bar links https://wiki.toolserver.org/view/User:Tparis/Index which is incomplete and has dead links.

Top bar for completeness: Home · Edit counter · Page History Statistics · Article blamer · CIDR · IP calculator · Index

Sidebar on some tools: Navigation
Stable tools

```
Home
Edit counter
Random Quotes
Edit summary counter
Is X an admin?
Top namespace edits
Pages created
RfA Votes
Automated edits
CIDR range contribs (NEW TOOL)
Quick edit counter (NEW TOOL)

Bug reports
View source
```

**Comment by Hedonil** [comment]
Unified to one design (and code base)
