### ISSUE TITLE
x-tools API?

### ISSUE THREAD

**Issue by nasirkhan** [x-tools/xtools-legacy#70]
Is there any API available for the x-tool?

I am going to build a stat report generator and i will need many of the stat data generated by x-tools. So instead to building the same tool i want to use this. having an API will be very helpful. can you please help me to find the way?

**Comment by willbeaufoy** [comment]
There is an [API](https://tools.wmflabs.org/xtools/api.php) but it's currently down. I'm trying to work out why.

**Comment by Matthewrbowker** [comment]
Hi, @nasirkhan 

Short answer to your question, yes we have an API. It is not documented, and is still a work in progress.  

We are moving over to the Wikimedia Foundation Phabricator for development of XTools. I've migrated your task there, you are welcome to watch it at https://phabricator.wikimedia.org/T171997
