### ISSUE TITLE
rfap: Highlight RfXs by outcome

### ISSUE THREAD

**Issue by enterprisey** [x-tools/xtools-legacy#71]
In the RfX Vote Calculator, each entry in the list of RfXs should indicate the result of that RfX.

For instance, if an entry says "2015-08-24  (121, 17, 3)    Wbm1058", then something should be highlighted with a green color (the timestamp, perhaps), and if an entry says " 2014-08-21   (42, 28, 4)     Dodger67", then the corresponding something should be highlighted with a red color.

**Comment by Matthewrbowker** [comment]
Hi, @APerson241 

We are moving over to the Wikimedia Foundation Phabricator for development of XTools. I've migrated your task there, you are welcome to watch it at https://phabricator.wikimedia.org/T171998
