### ISSUE TITLE
"Mainspace" header on Edit Counter in en.wp shows in Korean instead of English

### ISSUE THREAD

**Issue by jonesey95** [x-tools/xtools-legacy#72]
Copied from VPT on en.wp, 16 Sep 2015: "The heading of mainspace edits appears in Korean (일반 문서) when using the edit counter in English Wikipedia. The rest of the headings are in English. Same thing happens in the article creation counter when 일반 문서 appears to indicate the article creation heading. Does anyone know why? - User:Dr.K."

**Comment by atdt** [comment]
I hope you don't mind, but since I had no good alternative way of testing this, I simply applied the change on tool labs.
