### ISSUE TITLE
x-Tools doesn't show namespace properly on recently edited pages

### ISSUE THREAD

**Issue by Matthewrbowker** [x-tools/xtools-legacy#73]
See title.  The namespace is nonexistent, in the link or display of a recently edited page.  

<img width="1639" alt="screen shot 2015-09-22 at 19 40 11" src="https://cloud.githubusercontent.com/assets/802331/10036234/c6f6601a-6161-11e5-8904-535eacd6f538.png">

**Comment by KIDE777** [comment]
![123](https://cloud.githubusercontent.com/assets/15230396/10635863/f4501436-7825-11e5-80a3-bee76a4b6eeb.png)

Also the protocol is doubled. https://https//abcdefghij so the links can't be followed normally.

**Comment by atdt** [comment]
Fixed by #79 and #76
