### ISSUE TITLE
xtools-articleinfo does not work for outreachwiki

### ISSUE THREAD

**Issue by Cladis** [x-tools/xtools-legacy#74]
xtools-articleinfo does not work for outreachwiki. It founds no revisions for existing pages.

**Comment by Cladis** [comment]
Not just this xtool actually it seems.

**Comment by ValentinBrclz** [comment]
Same for frwiki.

**Comment by Cladis** [comment]
Mm, actually it looks like not working with outreachwiki still. Seem to work with frwiki though
