### ISSUE TITLE
Broken diffs

### ISSUE THREAD

**Issue by WikiLeo** [x-tools/xtools-legacy#78]
Hi there - Thanks for the best Responsibility/Transparency tool yet. When I click on any (diff) under "Latest edits, I get a "can't open" error. I think it's because "http" is doubled in the link. - Thanks again; Leo

**Comment by leee** [comment]
@atdt - if you'd be willing to abuse your bits again we could merge #76 and have it deployed so this is resolved.

**Comment by leee** [comment]
Er, NACK - the pr is not related to this issue.

**Comment by WikiLeo** [comment]
TYSMYG. i tried https://tools.wmflabs.org/xtools-ec/?user=LeoRomero&project=en.wikipedia.org again, but got zero data. This still works though: https://tools.wmflabs.org/guc/?user=LeoRomero

**Comment by WikiLeo** [comment]
NVM, works now. Thanks again, and Mabuhay!

**Comment by WikiLeo** [comment]
NVM NVM. is still broke. 

f.e: https://tools.wmflabs.org/xtools-ec/?user=LeoRomero&project=en.wikipedia.org 

when i click on (diff) - f.e on the Article Hypocrisy - I get a 404 https://tools.wmflabs.org/xtools-ec/en.wikipedia.org/w/index.php?title=Hypocrisy&diff=prev&oldid=695947988

Sorry.

<img width="1132" alt="screen shot 2015-12-21 at 12 13 45 pm" src="https://cloud.githubusercontent.com/assets/16326964/11940334/da798308-a7dc-11e5-9dc6-72c4a4884192.png">
