### ISSUE TITLE
Edit count uses wrong language for namespace label

### ISSUE THREAD

**Issue by Krinkle** [x-tools/xtools-legacy#82]
The "Top edited  pages" section at https://tools.wmflabs.org/xtools-ec/?user=Krinkle&project=en.wikipedia.org#topedited starts with an unexpected heading "Artículo".
<img width="377" alt="screen shot 2015-12-20 at 11 52 35" src="https://cloud.githubusercontent.com/assets/156867/11919762/30b53780-a710-11e5-91dc-992def2b5a0f.png">

**Comment by atdt** [comment]
Fixed in 4cecf0240d
