### ISSUE TITLE
Broken diffs : Part II

### ISSUE THREAD

**Issue by WikiLeo** [x-tools/xtools-legacy#83]
Left some comments on the previous ticket https://github.com/x-tools/xtools/issues/78#event-496915774. Just now occurred to me that i should have opened a new ticket instead. Sorry.  

Current (and previous) problem:

f.e: https://tools.wmflabs.org/xtools-ec/?user=LeoRomero&project=en.wikipedia.org 

when i click on (diff) - f.e on the Article Hypocrisy - I get a 404 https://tools.wmflabs.org/xtools-ec/en.wikipedia.org/w/index.php?title=Hypocrisy&diff=prev&oldid=695947988

Thanks & Mabuhay!
Leo
<img width="1132" alt="screen shot 2015-12-21 at 12 13 45 pm" src="https://cloud.githubusercontent.com/assets/16326964/11940468/bacbd7bc-a7dd-11e5-835a-ff212bb25bf8.png">

**Comment by ricordisamoa** [comment]
So I guess bf7a1d7465149c68889cc50dcc64da31166491ff and c4db233eadfe8c6f096197907d1bf33d6a103955 clashed :-)

**Comment by WikiLeo** [comment]
no diff probs now, thanks so much you guys, and Mabuhay!
