### ISSUE TITLE
adminstats seem to not work for *.wikimedia.org

### ISSUE THREAD

**Issue by Cladis** [x-tools/xtools-legacy#84]
As per the topic. Zero admins are returned.

**Comment by atdt** [comment]
Still doesn't work for chapter wikis.

**Comment by Matthewrbowker** [comment]
Appears to work for me, see https://tools.wmflabs.org/xtools/adminstats/?project=nyc.wikimedia.org&begin=2016-11-26&end= (I don't know how 8/8 is 80% of admins - guess we're re-inventing math?).  I believe this was fixed when I fixed #85
