### ISSUE TITLE
Link this GitHub repo from source/bugs links in footer

### ISSUE THREAD

**Issue by nemobis** [x-tools/xtools-legacy#9]
Per https://wikitech.wikimedia.org/wiki/Nova_Resource_Talk:Xtools#Code

**Comment by nemobis** [comment]
Particularly needed because the interface currently gives inconsistent information: "please report to Cyberpower678 using <a href="//en.wikipedia.org/wiki/User talk:Cyberpower678">the bug reporter.</a>"; "X!'s tools &middot; <a href="https://webchat.freenode.net/?channels=#xlabs">Bug reports</a>"

**Comment by cyberpower678** [comment]
Yea.  There was a bit of indecision with that.  My new helper and friend @Hedonil can help.

**Comment by Hedonil** [comment]
Yeah, fix'd this. Generic link to repo is now provided by default. Going through all subtools to add the the variable <subtoolname> to point at the very right point...
