### ISSUE TITLE
[AdminStats] Sorting by column does not work in French

### ISSUE THREAD

**Issue by Ltrlg** [x-tools/xtools-legacy#92]
Go to https://tools.wmflabs.org/xtools/adminstats/?project=fr.wikipedia.org&begin=2016-01-01&end=2016-04-09&uselang=fr an try to sort using the “delete” column (higher first).

The first one is Thibaut120094 with 961 deleted pages but both Lomita and Polmar have deleted more than 10,000 pages and should be displayed before. Looking at the end of the table, they are sorted as having deleted 10/11 pages. The sorting script seems not to handle French formating using spaces.

**Comment by urbanecm** [comment]
I can confirm this with Czech one. See https://tools.wmflabs.org/xtools/adminstats/?project=cs.wikipedia.org&begin=2016-04-24&end= . When you try to sort this using delete column (higher first) you can see that sorting works correctly only when sum of sysops actions don't exceed 999.

**Comment by tbertels** [comment]
It seems that sortable.js is encoded in windows-1252, so it would need to be converted to UTF-8 for this commit.

**Comment by Matthewrbowker** [comment]
This has been fixed in the rewrite, which will be deployed later this year.
